apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/lillegend0/https://github.com/lillegend0/gitops-lab.git
    targetRevision: main
    path: apps/demo/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
